/*
 * Generated by JasperReports - 18/01/2021, 9:12 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class hotel_1610935965111_34585 extends JREvaluator
{


    /**
     *
     */
    private JRFillVariable variable_PAGE_NUMBER = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 8 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "C:/Users/UwU/IdeaProjects/HotelManagement/src/resources/images/NicePng_green-leaf-design-png_9521126.png"; //$JR_EXPR_ID=9$
                break;
            }
            case 16 : 
            {
                value = "Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = " of " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=17$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 8 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "C:/Users/UwU/IdeaProjects/HotelManagement/src/resources/images/NicePng_green-leaf-design-png_9521126.png"; //$JR_EXPR_ID=9$
                break;
            }
            case 16 : 
            {
                value = "Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = " of " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=17$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 8 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = "C:/Users/UwU/IdeaProjects/HotelManagement/src/resources/images/NicePng_green-leaf-design-png_9521126.png"; //$JR_EXPR_ID=9$
                break;
            }
            case 16 : 
            {
                value = "Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = " of " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=17$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
